version: "2.3"
services: 
  react:
    container_name: react
    build: ./frontend
    ports: [3000:3000]
    volumes: 
      - /app/node_modules
      - ./frontend:/app
  laravel:
    container_name: laravel
    build: ./backend
    ports: [8000:8000]
    volumes: 
      - /app/vendor
      - ./backend:/app
    links: [mysql]
  mysql:
    container_name: mysql
    image: mysql:8.0
    expose: [3306]
    ports: [3306:3306]
    volumes: [database:/var/lib/mysql]
    environment:
      MYSQL_DATABASE: chatcha_db
      MYSQL_ROOT_PASSWORD: chatcha
  redis:
    container_name: redis
    image: redis:6.2.5-alpine
    ports: [6379:6379]
volumes:
  database:
    external: 
      name: mysql_data

